# Generated by Django 3.0.3 on 2020-04-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
